import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  MatCardModule,
  MatButtonModule,
  MatInputModule,
  MatTabsModule,
  MatSelectModule,
  MatCheckboxModule,
  MatTableModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatRadioModule,
  MatIconModule,
  MatDialogModule,
  MatPaginatorModule,
  MatGridListModule,
  MatSortModule,
  MatTooltipModule,
  MatRippleModule,
  MatProgressSpinnerModule,
  MatChipsModule,
  MatExpansionModule,
  MatButtonToggleModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatToolbarModule,
  MatSliderModule,
  MatSidenavModule,
  MatBadgeModule,
  MatProgressBarModule,
  MatListModule
} from '@angular/material';
// import { FlexLayoutModule, DEFAULT_CONFIG } from '@angular/flex-layout';

@NgModule({
  imports: [
    FormsModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatIconModule,
    MatDialogModule,
    MatInputModule,
    MatNativeDateModule,
    MatRadioModule,
    MatSelectModule,
    MatTabsModule,
    MatTooltipModule,
    ReactiveFormsModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSliderModule,
    MatBadgeModule,
    MatProgressBarModule,
    MatListModule
  ],
  exports: [
    FormsModule,
    MatCardModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatDialogModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatNativeDateModule,
    MatSelectModule,
    MatTabsModule,
    MatTableModule,
    MatPaginatorModule,
    MatRadioModule,
    MatSortModule,
    ReactiveFormsModule,
    MatTooltipModule,
    MatRippleModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSliderModule,
    MatToolbarModule,
    MatBadgeModule,
    MatProgressBarModule,
    MatSidenavModule,
    MatListModule
  ]
})

export class MaterialModule {}


